export enum FieldLength {
  NPI = 10,
  ViantCEID = 12,
  Contract = 14,
  FacilityName = 60,
  GroupName = 60,
  CorpEntityName = 60,
  LastName = 35,
  FirstName = 25,
  CredID = 15,
  CAQHID = 10,
  InternalID = 15,
  ViantHNSID = 12,
  Hcode = 15,
  Address = 55,
  City = 30,
  County = 30,
  Zip = 5,
  ContractSourceHCode = 15,
  ContractSourceName = 60,
}
